stages:
  - test
  - deploy

sast:
  variables:
    SAST_EXCLUDED_ANALYZERS: bandit, brakeman, flawfinder, gosec, kubesec, phpcs-security-audit,
      pmd-apex, security-code-scan, sobelow, spotbugs
  stage: test

deploy:
  image: node:gallium
  only:
    - tags
  stage: deploy
  script:
    - echo "npmAuthToken: \"${CI_JOB_TOKEN}\"" >> .yarnrc.yml
    - yarn npm publish

include:
  - template: Security/SAST.gitlab-ci.yml
  - template: Security/Dependency-Scanning.gitlab-ci.yml
  - template: Security/Secret-Detection.gitlab-ci.yml
  - template: Security/License-Scanning.gitlab-ci.yml
